name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: greeta-bookreview-01
  VERSION: ${{ github.sha }}

jobs:
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build container images
        run: |
          cd author-book-ui
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/author-book-ui:${{ env.VERSION }} .
          cd ../
          cd book-review-ui
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/book-review-ui:${{ env.VERSION }} .

      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container image
        run:  |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/author-book-ui:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/book-review-ui:${{ env.VERSION }}       

      - name: Publish container image (latest)
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/author-book-ui:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/author-book-ui:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/author-book-ui:latest
          
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/book-review-ui:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/book-review-ui:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/book-review-ui:latest